=== liuhaidongcoder/Demo/src/main/java/com/liuhaidongcoder/xml/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://www.58.com/eic/olap"
        targetNamespace="http://www.58.com/eic/olap"
        elementFormDefault="qualified">

    <simpleType name="storageTypeEnum">
        <restriction base="string">
            <enumeration value="REDIS"></enumeration>
            <enumeration value="WTABLE"></enumeration>
            <enumeration value="HBASE"></enumeration>
            <enumeration value="MYSQL"></enumeration>
            <enumeration value="TIDB"></enumeration>
            <enumeration value="DORIS"></enumeration>
            <enumeration value="CLICKHOUSE"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="propertyMeta">
        <sequence>
            <element name="name" type="string" minOccurs="1" maxOccurs="1"></element>
            <element name="value" type="string" minOccurs="1" maxOccurs="1"></element>
            <element name="desc" type="string" minOccurs="0" maxOccurs="1"></element>
        </sequence>
    </complexType>

    <!-- service类型 -->
    <complexType name="serviceMeta">
        <sequence>
            <element name="serviceName" type="string" minOccurs="1" maxOccurs="1"></element>
            <element name="serviceStorageType" type="tns:storageTypeEnum" minOccurs="1" maxOccurs="1"></element>
            <element name="desc" type="string" minOccurs="0" maxOccurs="1"></element>
            <element name="property" type="tns:propertyMeta"></element>
        </sequence>
    </complexType>

    <!-- app类型 -->
    <complexType name="appMeta">
        <sequence>
            <element name="service" type="tns:serviceMeta" minOccurs="1" maxOccurs="1"></element>
            <element name="property" type="tns:propertyMeta" minOccurs="0" maxOccurs="unbounded"></element>
        </sequence>
        <attribute name="id" type="token" ></attribute>
    </complexType>

    <!-- client类型 -->
    <complexType name="clientMeta">
        <sequence>
            <element name="app" minOccurs="0" maxOccurs="unbounded" type="tns:appMeta"/>
        </sequence>
        <attribute name="id" type="token" ></attribute>
    </complexType>

   <!-- clients类型 -->
    <complexType name="clientsMeta">
        <sequence>
            <element name="client" minOccurs="0" maxOccurs="unbounded" type="tns:clientMeta"/>
        </sequence>
    </complexType>

    <element name="clients" type="tns:clientsMeta"/>

</schema>

=== liuhaidongcoder/Demo/src/main/java/com/liuhaidongcoder/xml/configuration.xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns="http://www.58.com/eic/olap"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.58.com/eic/olap configuration.xsd ">
  <client id="xxx">
    <!--Zero or more repetitions:-->
    <app id="xxx">
      <service>
        <serviceName>string</serviceName>
        <serviceStorageType>TIDB</serviceStorageType>
        <!--Optional:-->
        <desc>string</desc>
        <property>
          <name>string</name>
          <value>string</value>
          <!--Optional:-->
          <desc>string</desc>
        </property>
      </service>
      <!--Zero or more repetitions:-->
      <property>
        <name>string</name>
        <value>string</value>
        <!--Optional:-->
        <desc>string</desc>
      </property>
    </app>
    <app id="xxx">
      <service>
        <serviceName>string</serviceName>
        <serviceStorageType>TIDB</serviceStorageType>
        <!--Optional:-->
        <desc>string</desc>
        <property>
          <name>string</name>
          <value>string</value>
          <!--Optional:-->
          <desc>string</desc>
        </property>
      </service>
      <!--Zero or more repetitions:-->
      <property>
        <name>string</name>
        <value>string</value>
        <!--Optional:-->
        <desc>string</desc>
      </property>
    </app>
  </client>
</clients>
